exports.document = function (req, res) {
    res.render('stat/document');
};

exports.system = function (req, res) {
    res.render('stat/system');
};

exports.documentStat = function (req, res) {
    var params = {
        documents: [{
            "date": "1",
            "sightings": 6
        }, {
            "date": "2",
            "sightings": 8
        }, {
            "date": "3",
            "sightings": 34
        }, {
            "date": "4",
            "sightings": 8
        }, {
            "date": "5",
            "sightings": 15
        }, {
            "date": "6",
            "sightings": 25
        }, {
            "date": "7",
            "sightings": 20
        }, {
            "date": "8",
            "sightings": 48
        }, {
            "date": "9",
            "sightings": 34
        }, {
            "date": "10",
            "sightings": 50
        }, {
            "date": "11",
            "sightings": 31
        }, {
            "date": "12",
            "sightings": 38
        }, {
            "date": "13",
            "sightings": 67
        }, {
            "date": "14",
            "sightings": 40
        }, {
            "date": "15",
            "sightings": 47
        }, {
            "date": "16",
            "sightings": 64
        }, {
            "date": "17",
            "sightings": 39
        }, {
            "date": "18",
            "sightings": 55
        }, {
            "date": "19",
            "sightings": 75
        }, {
            "date": "20",
            "sightings": 77
        }, {
            "date": "21",
            "sightings": 167
        }, {
            "date": "22",
            "sightings": 169
        }, {
            "date": "23",
            "sightings": 178
        }, {
            "date": "24",
            "sightings": 183
        }, {
            "date": "25",
            "sightings": 138
        }, {
            "date": "26",
            "sightings": 126
        }, {
            "date": "27",
            "sightings": 110
        }, {
            "date": "28",
            "sightings": 146
        }, {
            "date": "29",
            "sightings": 209
        }, {
            "date": "30",
            "sightings": 241
        }, {
            "date": "31",
            "sightings": 279
        }, {
            "date": "32",
            "sightings": 246
        }, {
            "date": "33",
            "sightings": 239
        }, {
            "date": "34",
            "sightings": 301
        }, {
            "date": "35",
            "sightings": 221
        }, {
            "date": "36",
            "sightings": 211
        }, {
            "date": "37",
            "sightings": 146
        }, {
            "date": "38",
            "sightings": 182
        }, {
            "date": "39",
            "sightings": 132
        }, {
            "date": "40",
            "sightings": 172
        }, {
            "date": "41",
            "sightings": 192
        }, {
            "date": "42",
            "sightings": 173
        }, {
            "date": "43",
            "sightings": 193
        }, {
            "date": "44",
            "sightings": 203
        }, {
            "date": "45",
            "sightings": 220
        }, {
            "date": "46",
            "sightings": 217
        }, {
            "date": "47",
            "sightings": 210
        }, {
            "date": "48",
            "sightings": 228
        }, {
            "date": "49",
            "sightings": 285
        }, {
            "date": "50",
            "sightings": 381
        }, {
            "date": "51",
            "sightings": 1336
        }, {
            "date": "52",
            "sightings": 862
        }, {
            "date": "53",
            "sightings": 1248
        }, {
            "date": "54",
            "sightings": 1812
        }, {
            "date": "55",
            "sightings": 2906
        }, {
            "date": "56",
            "sightings": 2780
        }, {
            "date": "57",
            "sightings": 3105
        }, {
            "date": "58",
            "sightings": 3176
        }, {
            "date": "59",
            "sightings": 3896
        }, {
            "date": "60",
            "sightings": 4208
        }, {
            "date": "61",
            "sightings": 3996
        }, {
            "date": "62",
            "sightings": 3590
        }, {
            "date": "63",
            "sightings": 4195
        }, {
            "date": "64",
            "sightings": 4705
        }, {
            "date": "65",
            "sightings": 4297
        }, {
            "date": "66",
            "sightings": 4531
        }],
        public_documents_status: [{
            "date": "12",
            "count": 228
        }, {
            "date": "13",
            "count": 285
        }, {
            "date": "14",
            "count": 381
        }, {
            "date": "15",
            "count": 1336
        }, {
            "date": "16",
            "count": 862
        }, {
            "date": "17",
            "count": 1248
        }, {
            "date": "18",
            "count": 1812
        }, {
            "date": "19",
            "count": 2906
        }, {
            "date": "20",
            "count": 2780
        }, {
            "date": "22",
            "count": 3105
        }, {
            "date": "23",
            "count": 3176
        }, {
            "date": "24",
            "count": 3896
        }, {
            "date": "25",
            "count": 4208
        }, {
            "date": "26",
            "count": 3996
        }, {
            "date": "27",
            "count": 3590
        }, {
            "date": "28",
            "count": 4195
        }, {
            "date": "29",
            "count": 4705
        }, {
            "date": "30",
            "count": 4297
        }, {
            "date": "31",
            "count": 2531
        }],
        attached_file_size: [{
            "date": "2",
            "count": "1228"
        }, {
            "date": "3",
            "count": "1285"
        }, {
            "date": "4",
            "count": "1381"
        }, {
            "date": "5",
            "count": "1336"
        }, {
            "date": "6",
            "count": "1862"
        }, {
            "date": "7",
            "count": "1248"
        }, {
            "date": "8",
            "count": "1812"
        }, {
            "date": "9",
            "count": "2906"
        }, {
            "date": "10",
            "count": "2780"
        }, {
            "date": "11",
            "count": "3105"
        }, {
            "date": "12",
            "count": "3176"
        }, {
            "date": "13",
            "count": "3896"
        }, {
            "date": "14",
            "count": "4208"
        }, {
            "date": "15",
            "count": "3996"
        }, {
            "date": "16",
            "count": "3590"
        }, {
            "date": "17",
            "count": "4195"
        }, {
            "date": "18",
            "count": "4705"
        }, {
            "date": "19",
            "count": "4297"
        }, {
            "date": "20",
            "count": "2531"
        }]
    };

    res.json(params);
};

exports.systemStat = function (req, res) {
    var params = {};

    res.json(params);
};